<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_B" Id="{bfba4680-db9d-47f4-9ef8-cb7dce3ea440}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_B
VAR_OUTPUT
	sum : INT;
END_VAR
VAR
	ppointer : POINTER TO FB_A;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[sum := ppointer^.Sum(2,67);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>