<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{7b316274-9c8c-43fa-ac00-fbcea73629c0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fbRStopwatch		: RTimers.Timer(E_timer_type.RStopwatch);
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbRStopwatch();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>