<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="P_Example_1" Id="{6b528a2e-6c61-400c-b708-26ec986ea447}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Example_1
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Example_1_TONs();
P_Example_1_TOFs();]]></ST>
    </Implementation>
    <LineIds Name="P_Example_1">
      <LineId Id="5" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>